version: '3.4'

services:
  tree-sql:
    container_name: tree-sql
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - ~/.vsdbg:/remote_debugger:rw

  tree-elasticstack:
    container_name: tree-elasticstack
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - ~/.vsdbg:/remote_debugger:rw