version: '3.4'

services:
  tree-sql-path-based:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PathBasedOrganizationDb=Server=db;Database=Trees.PathBased.OrganizationDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5010:5000"

  tree-sql-closure-table:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__ClosureTableOrganizationDb=Server=db;Database=Trees.ClosureTable.OrganizationDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5020:5000"

  tree-elasticstack:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ElasticSearchUrl=http://elastic-search:9200
    ports:
      - "5030:5000"

  tree-mongo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__OrganizationDb=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    ports:
      - "5040:5000"

  db:
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    mem_limit: 2048M
    ulimits:
      memlock:
        soft: -1
        hard: -1

  mongo:
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    mem_limit: 2048M
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elastic-search:
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
    mem_limit: 2048M
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

volumes:
  sqldata:
  mongodata:
  esdata01:
  kibanadata:
