version: '3.4'

services:
  tree-sql-path-based:
    image: tree.sql-path-based:${TAG:-latest}
    build:
      context: .
      dockerfile: SQL.PathBased/Dockerfile

  tree-sql-closure-table:
    image: tree.sql-closure-table:${TAG:-latest}
    build:
      context: .
      dockerfile: SQL.ClosureTable/Dockerfile

  tree-elasticstack:
    image: tree.elasticstack:${TAG:-latest}
    build:
      context: .
      dockerfile: ElasticStack/Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
