version: '3.4'

services:
  tree-sql-path-based:
    container_name: tree-sql-path-based
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - ~/.vsdbg:/remote_debugger:rw

  tree-sql-closure-table:
    container_name: tree-sql-closure-table
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - ~/.vsdbg:/remote_debugger:rw

  tree-elasticstack:
    container_name: tree-elasticstack
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - ~/.vsdbg:/remote_debugger:rw

  tree-mongo:
    container_name: tree-mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - ~/.vsdbg:/remote_debugger:rw
